from __future__ import annotations

import os
import shlex
import shutil
from pathlib import Path
from typing import Dict, Iterable, List, Optional

from .models import FailureEvent, WaveformWindow


def build_waveform_window(
    first_failure: Optional[FailureEvent], before_ns: float, after_ns: float
) -> WaveformWindow:
    center = first_failure.time_ns if first_failure else None
    if center is None:
        return WaveformWindow(None, None, None, before_ns, after_ns)
    return WaveformWindow(center, max(0.0, center - before_ns), center + after_ns, before_ns, after_ns)


def discover_waveform_tools() -> Dict[str, str]:
    candidates = ["verdi", "fsdb2vcd", "nWave"]
    return {name: path for name in candidates if (path := shutil.which(name))}


def write_signal_list(signals: Iterable[str], out_dir: Path) -> Path:
    signal_list = out_dir / "signal_list.txt"
    lines = [signal for signal in signals if signal]
    signal_list.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return signal_list


def write_verdi_launch_files(
    *,
    out_dir: Path,
    fsdb_path: Optional[Path],
    filelist: Optional[Path],
    top: Optional[str],
    signals: List[str],
    window: WaveformWindow,
) -> Dict[str, Path]:
    artifacts: Dict[str, Path] = {}
    signal_list = write_signal_list(signals, out_dir)
    artifacts["signal_list"] = signal_list

    start_value = "" if window.start_ns is None else str(window.start_ns)
    end_value = "" if window.end_ns is None else str(window.end_ns)
    tcl_path = out_dir / "verdi_open.tcl"
    tcl_lines = [
        "# Generated by vcs_failure_explainer.py",
        "# Load this after opening Verdi/nWave if your local Verdi version supports these commands.",
        "# The shell launcher below is the canonical generated entry point.",
        f"set failure_window_start_ns {start_value}",
        f"set failure_window_end_ns {end_value}",
        f"set ranked_signal_list_file {{{signal_list}}}",
        "",
        "# Ranked signals:",
    ]
    tcl_lines.extend(f"#   {signal}" for signal in signals)
    tcl_path.write_text("\n".join(tcl_lines) + "\n", encoding="utf-8")
    artifacts["verdi_tcl"] = tcl_path

    if fsdb_path:
        shell_path = out_dir / "open_verdi.sh"
        cmd = ["verdi", "-ssf", str(fsdb_path)]
        if filelist:
            cmd.extend(["-f", str(filelist)])
        if top:
            cmd.extend(["-top", top])

        shell_lines = [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "",
            "# Generated by vcs_failure_explainer.py",
            f"# Failure window: {window.label()}",
            f"# Ranked signals: {signal_list}",
            "# Add version-specific waveform commands from verdi_open.tcl after launch if desired.",
            "",
            " ".join(shlex.quote(part) for part in cmd) + ' "${EXTRA_VERDI_ARGS[@]:-}"',
        ]
        shell_path.write_text("\n".join(shell_lines) + "\n", encoding="utf-8")
        os.chmod(shell_path, 0o755)
        artifacts["verdi_shell"] = shell_path

    return artifacts
